GET http://localhost:3001/saisons

####

GET http://localhost:3001/saisons/638caf00b5b59180c660f16c

###
POST http://localhost:3001/saisons
Content-Type: application/json

{
    "saisonNumber": "7",
    "deathsNumber": "350"
}

###

DELETE http://localhost:3001/saisons/638c7853b5b59180c660f14f

###

PATCH  http://localhost:3001/saisons/638caf00b5b59180c660f16c
Content-Type: application/json

{
    "deathsNumber": "355"
}